name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar pacotes
        run: dotnet restore src/Portfolio/Portfolio/Portfolio.csproj

      - name: Publicar projeto
        run: dotnet publish src/Portfolio/Portfolio/Portfolio.csproj -c Release -o publish

      - name: Atualizar <base href>
        run: |
          sed -i 's|<base href="/" />|<base href="/Portfolio/" />|' publish/wwwroot/index.html

      - name: Copiar arquivos para pasta de deploy
        run: |
          mkdir deploy
          cp -r publish/wwwroot/* deploy/
          touch deploy/.nojekyll
          cp deploy/index.html deploy/404.html

      - name: Publicar no GitHub Pages (branch gh-pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
